
kind: pipeline
type: docker
name: auth-service-build-img-worksn't

trigger:
  branch:
    - master
  event:
    - push

platform:
  os: linux
  arch: arm

steps:
  #- name: build_and_publish-amd64
  #  image:  plugins/docker
  #  settings:
  #    repo: bajaks/webshop-api-microservices.auth-service
  #    username:
  #      from_secret:  dockerhub_username 
  #    password:
  #      from_secret:  dockerhub_pass
  #      #tags:
  #      #  - v1.0
  #    auto_tag: true
  #    auto_tag_suffix:  linux-amd64
- name: build_and_publish-arm
  image:  plugins/docker
  settings:
    repo: bajaks/webshop-api-microservices.auth-service
    dockerfile: Dockerfile-arm
    username:
      from_secret:  dockerhub_username 
    password:
      from_secret:  dockerhub_pass
      #tags:
      #  - v1.0.0
    auto_tag: true
    auto_tag:suffix:  linux-arm
    build_args:
      - ARCH=arm
      - REPO=arm32v7
