
kind: pipeline
type: docker
name: auth-service-build-arm

trigger:
  branch:
    - master
  event:
    - push

platform:
  os: linux
  arch: arm

steps:
- name: build_and_publish-arm
  image:  plugins/docker
  settings:
    repo: bajaks/webshop-api-microservices.auth-service
    dockerfile: Dockerfile-arm
    username:
      from_secret:  dockerhub_username 
    password:
      from_secret:  dockerhub_pass
      #tags:
      #  - v1.0.0
      #auto_tag:suffix:  linux-arm
    tags: ${DRONE_BUILD_NUMBER}-arm32v7
- name: git-clone
  image:  alpine/git
  commands:
    - git clone http://192.168.1.108:3000/Baja-KS/WebshopAPI-deployment.git
- name: change-img-version
  image:  mikefarah/yq:arm32v7-latest
  commands: 
    - TAG=${DRONE_BUILD_NUMBER}-arm32v7 yq e -i '.spec.template.spec.containers[0].image = "bajaks/webshop-api-microservices.auth-service:strenv(TAG)" ' WebshopAPI-deployment/auth-service.yaml
- name: git-push
  image:  alpine/git
  commands:
    - cd WebshopAPI-deployment
    - git add auth-service.yaml
    - git commit -m "Change image version to ${DRONE_BUILD_NUMBER}"
    - git push origin master


---


kind: pipeline
type: docker
name: auth-service-build-amd64

trigger:
  branch:
    - master
  event:
    - push

platform:
  os: linux
  arch: amd64

steps:
  - name: build_and_publish-amd64
    image:  plugins/docker
    settings:
      repo: bajaks/webshop-api-microservices.auth-service
      username:
        from_secret:  dockerhub_username 
      password:
        from_secret:  dockerhub_pass
        #tags:
        #  - v1.0
      tags: ${DRONE_BUILD_NUMBER}-amd64
