
kind: pipeline
type: docker
name: auth-service-build-img-worksn't

trigger:
  branch:
    - master
  event:
    - push

steps:
- name: build_and_publish
  image:  plugins/docker
  settings:
    repo: bajaks/webshop-api-microservices.auth-service
    username: bajaks
    password: 1776Baja210
    auto_tag: true
