
kind: pipeline
type: docker
name: auth-service-build-img-worksn't

trigger:
  branch:
    - master
  event:
    - push

steps:
- name: build_and_publish
  image:  plugins/docker
  settings:
    repo: bajaks/webshop-api-microservices.auth-service
    username:
      from_secret:  dockerhub_username 
    password:
      from_secret:  dockerhub_pass
    tags:
      - v1.0
      - v1.1  
