
kind: pipeline
type: docker
name: auth-service-build-arm

trigger:
  branch:
    - master
  event:
    - push

platform:
  os: linux
  arch: arm

steps:
- name: build_and_publish-arm
  image:  plugins/docker
  settings:
    repo: bajaks/webshop-api-microservices.auth-service
    dockerfile: Dockerfile-arm
    username:
      from_secret:  dockerhub_username 
    password:
      from_secret:  dockerhub_pass
      #tags:
      #  - v1.0.0
      #auto_tag:suffix:  linux-arm
    tags: ${DRONE_BUILD_NUMBER}-arm

---


kind: pipeline
type: docker
name: auth-service-build-amd64

trigger:
  branch:
    - master
  event:
    - push

platform:
  os: linux
  arch: amd64

steps:
  - name: build_and_publish-amd64
    image:  plugins/docker
    settings:
      repo: bajaks/webshop-api-microservices.auth-service
      username:
        from_secret:  dockerhub_username 
      password:
        from_secret:  dockerhub_pass
        #tags:
        #  - v1.0
      tags: ${DRONE_BUILD_NUMBER}
