version: 0.2

env:
  variables:
    GOOS: linux
    GO111MODULE: "on"
    DOCKER_REGISTRY: 405674440388.dkr.ecr.eu-west-2.amazonaws.com
    DOCKER_REPO: 405674440388.dkr.ecr.eu-west-2.amazonaws.com/webshop-api-auth-ms

phases:
  pre_build:
    commands:
      # - IMAGE_TAG=${CODEBUILD_BUILD_NUMBER}
      - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  build:
    commands:
      - docker build -t ${DOCKER_REPO}:${CODEBUILD_BUILD_NUMBER} .
      - 
  post_build:
    commands:
      - docker push ${DOCKER_REPO}:${CODEBUILD_BUILD_NUMBER}
      - echo Build completed on `date`
# artifacts:
#   files:
#     - target/messageUtil-1.0.jar